// GENERADO POR scripts/build_moderation_list.py — NO EDITAR A MANO.
//
// Fuente: assets/moderation/terminos-vetados.json
// El espejo de este archivo es functions/src/moderation/vetted_terms.g.ts, y
// sale del MISMO origen en la misma corrida.
library;

/// Version del corpus. Sube cuando cambia la lista.
const int kVettedTermsVersion = 1;

/// `á` -> `a`, `ñ` -> `n`. Sale de `unicodedata` de Python, no de una tabla
/// escrita a mano: ni Dart ni TypeScript traen NFD en su biblioteca estandar,
/// y dos tablas a mano divergen en la tercera vocal rara.
const Map<String, String> kVettedFold = {
  'à': 'a',
  'á': 'a',
  'â': 'a',
  'ã': 'a',
  'ä': 'a',
  'å': 'a',
  'ç': 'c',
  'è': 'e',
  'é': 'e',
  'ê': 'e',
  'ë': 'e',
  'ì': 'i',
  'í': 'i',
  'î': 'i',
  'ï': 'i',
  'ñ': 'n',
  'ò': 'o',
  'ó': 'o',
  'ô': 'o',
  'õ': 'o',
  'ö': 'o',
  'ù': 'u',
  'ú': 'u',
  'û': 'u',
  'ü': 'u',
  'ý': 'y',
  'ÿ': 'y',
  'ā': 'a',
  'ă': 'a',
  'ą': 'a',
  'ć': 'c',
  'ĉ': 'c',
  'ċ': 'c',
  'č': 'c',
  'ď': 'd',
  'ē': 'e',
  'ĕ': 'e',
  'ė': 'e',
  'ę': 'e',
  'ě': 'e',
  'ĝ': 'g',
  'ğ': 'g',
  'ġ': 'g',
  'ģ': 'g',
  'ĥ': 'h',
  'ĩ': 'i',
  'ī': 'i',
  'ĭ': 'i',
  'į': 'i',
  'ĵ': 'j',
  'ķ': 'k',
  'ĺ': 'l',
  'ļ': 'l',
  'ľ': 'l',
  'ń': 'n',
  'ņ': 'n',
  'ň': 'n',
  'ō': 'o',
  'ŏ': 'o',
  'ő': 'o',
  'ŕ': 'r',
  'ŗ': 'r',
  'ř': 'r',
  'ś': 's',
  'ŝ': 's',
  'ş': 's',
  'š': 's',
  'ţ': 't',
  'ť': 't',
  'ũ': 'u',
  'ū': 'u',
  'ŭ': 'u',
  'ů': 'u',
  'ű': 'u',
  'ų': 'u',
  'ŵ': 'w',
  'ŷ': 'y',
  'ź': 'z',
  'ż': 'z',
  'ž': 'z',
  'ơ': 'o',
  'ư': 'u',
  'ǎ': 'a',
  'ǐ': 'i',
  'ǒ': 'o',
  'ǔ': 'u',
  'ǖ': 'u',
  'ǘ': 'u',
  'ǚ': 'u',
  'ǜ': 'u',
  'ǟ': 'a',
  'ǡ': 'a',
  'ǧ': 'g',
  'ǩ': 'k',
  'ǫ': 'o',
  'ǭ': 'o',
  'ǰ': 'j',
  'ǵ': 'g',
  'ǹ': 'n',
  'ǻ': 'a',
  'ȁ': 'a',
  'ȃ': 'a',
  'ȅ': 'e',
  'ȇ': 'e',
  'ȉ': 'i',
  'ȋ': 'i',
  'ȍ': 'o',
  'ȏ': 'o',
  'ȑ': 'r',
  'ȓ': 'r',
  'ȕ': 'u',
  'ȗ': 'u',
  'ș': 's',
  'ț': 't',
  'ȟ': 'h',
  'ȧ': 'a',
  'ȩ': 'e',
  'ȫ': 'o',
  'ȭ': 'o',
  'ȯ': 'o',
  'ȱ': 'o',
  'ȳ': 'y'
};

/// Deshacer leet: `0` -> `o`, `@` -> `a`.
const Map<String, String> kVettedLeet = {
  '!': 'i',
  '\$': 's',
  '0': 'o',
  '1': 'i',
  '3': 'e',
  '4': 'a',
  '5': 's',
  '7': 't',
  '@': 'a'
};

/// Los simbolos de `kVettedLeet` que SOLO se traducen con letra a los dos
/// lados. Sin esa regla `puta!` normaliza a `putai` y deja de matchear.
const Set<String> kVettedLeetOnlyBetweenLetters = {'!', '\$', '@'};

/// Runs de este largo o mas colapsan a un caracter: `putooooo` -> `puto`.
/// Tres y no dos: el castellano tiene dobles (`carro`, `perro`) pero no
/// triples.
const int kVettedCollapseMin = 3;

/// Largo maximo de un fragmento para que la pasada antievasion lo PEGUE con el
/// de al lado. Ver el porque en scripts/build_moderation_list.py.
const int kVettedJoinMaxFragment = 3;

/// Rangos `[desde, hasta]` de marcas combinantes (categoria Unicode `Mn`),
/// aplanados. Se descartan antes de tokenizar: sin esto, el mismo texto llega
/// descompuesto —`u` + U+0301 en vez de `ú`— la marca parte el token en dos y
/// el termino no matchea, mientras que la forma precompuesta si se bloquea.
/// Los dos se ven IDENTICOS en pantalla.
const List<int> kVettedCombiningRanges = [
  0x0300,
  0x036F,
  0x0483,
  0x0487,
  0x0591,
  0x05BD,
  0x05BF,
  0x05BF,
  0x05C1,
  0x05C2,
  0x05C4,
  0x05C5,
  0x05C7,
  0x05C7,
  0x0610,
  0x061A,
  0x064B,
  0x065F,
  0x0670,
  0x0670,
  0x06D6,
  0x06DC,
  0x06DF,
  0x06E4,
  0x06E7,
  0x06E8,
  0x06EA,
  0x06ED,
  0x0711,
  0x0711,
  0x0730,
  0x074A,
  0x07A6,
  0x07B0,
  0x07EB,
  0x07F3,
  0x07FD,
  0x07FD,
  0x0816,
  0x0819,
  0x081B,
  0x0823,
  0x0825,
  0x0827,
  0x0829,
  0x082D,
  0x0859,
  0x085B,
  0x0897,
  0x089F,
  0x08CA,
  0x08E1,
  0x08E3,
  0x0902,
  0x093A,
  0x093A,
  0x093C,
  0x093C,
  0x0941,
  0x0948,
  0x094D,
  0x094D,
  0x0951,
  0x0957,
  0x0962,
  0x0963,
  0x0981,
  0x0981,
  0x09BC,
  0x09BC,
  0x09C1,
  0x09C4,
  0x09CD,
  0x09CD,
  0x09E2,
  0x09E3,
  0x09FE,
  0x09FE,
  0x0A01,
  0x0A02,
  0x0A3C,
  0x0A3C,
  0x0A41,
  0x0A42,
  0x0A47,
  0x0A48,
  0x0A4B,
  0x0A4D,
  0x0A51,
  0x0A51,
  0x0A70,
  0x0A71,
  0x0A75,
  0x0A75,
  0x0A81,
  0x0A82,
  0x0ABC,
  0x0ABC,
  0x0AC1,
  0x0AC5,
  0x0AC7,
  0x0AC8,
  0x0ACD,
  0x0ACD,
  0x0AE2,
  0x0AE3,
  0x0AFA,
  0x0AFF,
  0x0B01,
  0x0B01,
  0x0B3C,
  0x0B3C,
  0x0B3F,
  0x0B3F,
  0x0B41,
  0x0B44,
  0x0B4D,
  0x0B4D,
  0x0B55,
  0x0B56,
  0x0B62,
  0x0B63,
  0x0B82,
  0x0B82,
  0x0BC0,
  0x0BC0,
  0x0BCD,
  0x0BCD,
  0x0C00,
  0x0C00,
  0x0C04,
  0x0C04,
  0x0C3C,
  0x0C3C,
  0x0C3E,
  0x0C40,
  0x0C46,
  0x0C48,
  0x0C4A,
  0x0C4D,
  0x0C55,
  0x0C56,
  0x0C62,
  0x0C63,
  0x0C81,
  0x0C81,
  0x0CBC,
  0x0CBC,
  0x0CBF,
  0x0CBF,
  0x0CC6,
  0x0CC6,
  0x0CCC,
  0x0CCD,
  0x0CE2,
  0x0CE3,
  0x0D00,
  0x0D01,
  0x0D3B,
  0x0D3C,
  0x0D41,
  0x0D44,
  0x0D4D,
  0x0D4D,
  0x0D62,
  0x0D63,
  0x0D81,
  0x0D81,
  0x0DCA,
  0x0DCA,
  0x0DD2,
  0x0DD4,
  0x0DD6,
  0x0DD6,
  0x0E31,
  0x0E31,
  0x0E34,
  0x0E3A,
  0x0E47,
  0x0E4E,
  0x0EB1,
  0x0EB1,
  0x0EB4,
  0x0EBC,
  0x0EC8,
  0x0ECE,
  0x0F18,
  0x0F19,
  0x0F35,
  0x0F35,
  0x0F37,
  0x0F37,
  0x0F39,
  0x0F39,
  0x0F71,
  0x0F7E,
  0x0F80,
  0x0F84,
  0x0F86,
  0x0F87,
  0x0F8D,
  0x0F97,
  0x0F99,
  0x0FBC,
  0x0FC6,
  0x0FC6,
  0x102D,
  0x1030,
  0x1032,
  0x1037,
  0x1039,
  0x103A,
  0x103D,
  0x103E,
  0x1058,
  0x1059,
  0x105E,
  0x1060,
  0x1071,
  0x1074,
  0x1082,
  0x1082,
  0x1085,
  0x1086,
  0x108D,
  0x108D,
  0x109D,
  0x109D,
  0x135D,
  0x135F,
  0x1712,
  0x1714,
  0x1732,
  0x1733,
  0x1752,
  0x1753,
  0x1772,
  0x1773,
  0x17B4,
  0x17B5,
  0x17B7,
  0x17BD,
  0x17C6,
  0x17C6,
  0x17C9,
  0x17D3,
  0x17DD,
  0x17DD,
  0x180B,
  0x180D,
  0x180F,
  0x180F,
  0x1885,
  0x1886,
  0x18A9,
  0x18A9,
  0x1920,
  0x1922,
  0x1927,
  0x1928,
  0x1932,
  0x1932,
  0x1939,
  0x193B,
  0x1A17,
  0x1A18,
  0x1A1B,
  0x1A1B,
  0x1A56,
  0x1A56,
  0x1A58,
  0x1A5E,
  0x1A60,
  0x1A60,
  0x1A62,
  0x1A62,
  0x1A65,
  0x1A6C,
  0x1A73,
  0x1A7C,
  0x1A7F,
  0x1A7F,
  0x1AB0,
  0x1ABD,
  0x1ABF,
  0x1ACE,
  0x1B00,
  0x1B03,
  0x1B34,
  0x1B34,
  0x1B36,
  0x1B3A,
  0x1B3C,
  0x1B3C,
  0x1B42,
  0x1B42,
  0x1B6B,
  0x1B73,
  0x1B80,
  0x1B81,
  0x1BA2,
  0x1BA5,
  0x1BA8,
  0x1BA9,
  0x1BAB,
  0x1BAD,
  0x1BE6,
  0x1BE6,
  0x1BE8,
  0x1BE9,
  0x1BED,
  0x1BED,
  0x1BEF,
  0x1BF1,
  0x1C2C,
  0x1C33,
  0x1C36,
  0x1C37,
  0x1CD0,
  0x1CD2,
  0x1CD4,
  0x1CE0,
  0x1CE2,
  0x1CE8,
  0x1CED,
  0x1CED,
  0x1CF4,
  0x1CF4,
  0x1CF8,
  0x1CF9,
  0x1DC0,
  0x1DFF,
  0x20D0,
  0x20DC,
  0x20E1,
  0x20E1,
  0x20E5,
  0x20F0,
  0x2CEF,
  0x2CF1,
  0x2D7F,
  0x2D7F,
  0x2DE0,
  0x2DFF,
  0x302A,
  0x302D,
  0x3099,
  0x309A,
  0xA66F,
  0xA66F,
  0xA674,
  0xA67D,
  0xA69E,
  0xA69F,
  0xA6F0,
  0xA6F1,
  0xA802,
  0xA802,
  0xA806,
  0xA806,
  0xA80B,
  0xA80B,
  0xA825,
  0xA826,
  0xA82C,
  0xA82C,
  0xA8C4,
  0xA8C5,
  0xA8E0,
  0xA8F1,
  0xA8FF,
  0xA8FF,
  0xA926,
  0xA92D,
  0xA947,
  0xA951,
  0xA980,
  0xA982,
  0xA9B3,
  0xA9B3,
  0xA9B6,
  0xA9B9,
  0xA9BC,
  0xA9BD,
  0xA9E5,
  0xA9E5,
  0xAA29,
  0xAA2E,
  0xAA31,
  0xAA32,
  0xAA35,
  0xAA36,
  0xAA43,
  0xAA43,
  0xAA4C,
  0xAA4C,
  0xAA7C,
  0xAA7C,
  0xAAB0,
  0xAAB0,
  0xAAB2,
  0xAAB4,
  0xAAB7,
  0xAAB8,
  0xAABE,
  0xAABF,
  0xAAC1,
  0xAAC1,
  0xAAEC,
  0xAAED,
  0xAAF6,
  0xAAF6,
  0xABE5,
  0xABE5,
  0xABE8,
  0xABE8,
  0xABED,
  0xABED,
  0xFB1E,
  0xFB1E,
  0xFE00,
  0xFE0F,
  0xFE20,
  0xFE2F
];

/// Terminos de severidad `block` de UNA palabra, ya normalizados.
const Set<String> kVettedBlockWords = {
  'chupapija',
  'chupapijas',
  'cojer',
  'concha',
  'conchas',
  'conchuda',
  'conchudo',
  'culiar',
  'garcha',
  'garchame',
  'garchar',
  'hdp',
  'koncha',
  'kulo',
  'lctm',
  'marica',
  'maricon',
  'maricones',
  'matate',
  'mogolica',
  'mogolico',
  'mogolicos',
  'pedofila',
  'pedofilia',
  'pedofilo',
  'pija',
  'pijas',
  'pornhub',
  'porno',
  'pornografia',
  'puta',
  'putas',
  'putazo',
  'putito',
  'puto',
  'putos',
  'pvta',
  'pvtas',
  'pvto',
  'pvtos',
  'sidoso',
  'subnormal',
  'suicidate',
  'tortillera',
  'travuco',
  'trolo',
  'trolos',
  'verga',
  'vergas',
  'zoofilia'
};

/// Terminos de severidad `block` de VARIAS palabras, como secuencia de tokens.
const List<List<String>> kVettedBlockPhrases = [
  ['andate', 'a', 'la', 'concha'],
  ['andate', 'a', 'morir'],
  ['chupame', 'la', 'pija'],
  ['colgate', 'de', 'un', 'arbol'],
  ['gorda', 'de', 'mierda'],
  ['gordo', 'de', 'mierda'],
  ['hija', 'de', 'puta'],
  ['hijo', 'de', 'puta'],
  ['hijos', 'de', 'puta'],
  ['la', 'concha', 'de', 'su', 'madre'],
  ['la', 'concha', 'de', 'tu', 'madre'],
  ['muerta', 'de', 'hambre'],
  ['muerto', 'de', 'hambre'],
  ['negra', 'de', 'mierda'],
  ['negro', 'de', 'mierda'],
  ['ojala', 'te', 'mueras'],
  ['retrasado', 'mental'],
  ['te', 'reviento'],
  ['te', 'voy', 'a', 'cagar', 'a', 'trompadas'],
  ['te', 'voy', 'a', 'matar'],
  ['te', 'voy', 'a', 'reventar'],
  ['vaca', 'de', 'mierda']
];

/// Terminos de severidad `review` de UNA palabra.
const Set<String> kVettedReviewWords = {
  'coger',
  'cogerte',
  'culo',
  'culos',
  'estupida',
  'estupido',
  'forra',
  'forro',
  'gil',
  'gila',
  'idiota',
  'imbecil',
  'pelotuda',
  'pelotudas',
  'pelotudo',
  'pelotudos',
  'proana',
  'promia',
  'sorete',
  'tarada',
  'tarado',
  'tetas',
  'thinspiration',
  'thinspo'
};

/// Terminos de severidad `review` de VARIAS palabras.
const List<List<String>> kVettedReviewPhrases = [
  ['dejar', 'de', 'comer', 'para'],
  ['manga', 'de', 'inutiles'],
  ['pro', 'ana'],
  ['vomitar', 'despues', 'de', 'comer']
];

/// Subconjunto para la pasada antievasion: subcadena sobre el texto sin
/// separadores. Chico y de severidad alta a proposito — ver el JSON fuente.
const List<String> kVettedAntiEvasion = [
  'chupapija',
  'conchudo',
  'garchame',
  'garchar',
  'maricon',
  'mogolico',
  'pedofilia',
  'pedofilo',
  'pornhub',
  'putazo',
  'puto',
  'sidoso',
  'tortillera',
  'travuco',
  'trolo',
  'zoofilia'
];

/// Palabras legitimas que contienen un termino de `kVettedAntiEvasion`. Se
/// sacan del texto antes de la pasada B.
const Set<String> kVettedAllowlist = {
  'amputo',
  'computo',
  'computos',
  'controlo',
  'descontrolo',
  'disputo',
  'imputo',
  'reputo'
};

/// Corpus de conformidad. La suite de TypeScript corre EXACTAMENTE estos
/// mismos casos: si los dos veredictos no coinciden, una de las dos se pone
/// roja. Ninguna de las dos escribe sus expectativas a mano.
const List<({String texto, String espera, String normalizado, String por})>
    kVettedCases = [
  (
    texto: 'computadora',
    espera: 'ok',
    normalizado: 'computadora',
    por: 'contiene `puta`'
  ),
  (
    texto: 'me lo anote en la computadora',
    espera: 'ok',
    normalizado: 'me lo anote en la computadora',
    por: 'contiene `puta`'
  ),
  (
    texto: 'calculo',
    espera: 'ok',
    normalizado: 'calculo',
    por: 'contiene `culo`'
  ),
  (
    texto: 'cálculo',
    espera: 'ok',
    normalizado: 'calculo',
    por: 'contiene `culo`, con acento'
  ),
  (
    texto: 'disputa',
    espera: 'ok',
    normalizado: 'disputa',
    por: 'contiene `puta`'
  ),
  (
    texto: 'reputación',
    espera: 'ok',
    normalizado: 'reputacion',
    por: 'contiene `puta`'
  ),
  (
    texto: 'sexteto',
    espera: 'ok',
    normalizado: 'sexteto',
    por: 'contiene `sex`'
  ),
  (
    texto: 'escocia',
    espera: 'ok',
    normalizado: 'escocia',
    por: 'falso positivo clasico'
  ),
  (
    texto: 'cuatro series para el musculo dorsal',
    espera: 'ok',
    normalizado: 'cuatro series para el musculo dorsal',
    por: '`musculo` contiene `culo`: el caso de ESTE producto'
  ),
  (
    texto: 'trabajo de musculacion tres veces por semana',
    espera: 'ok',
    normalizado: 'trabajo de musculacion tres veces por semana',
    por: 'vocabulario central de la app'
  ),
  (
    texto: 'el computo de las series',
    espera: 'ok',
    normalizado: 'el computo de las series',
    por: 'contiene `puto` — el que obliga a la allowlist'
  ),
  (
    texto: 'me puse el pijama',
    espera: 'ok',
    normalizado: 'me puse el pijama',
    por: 'contiene `pija`'
  ),
  (
    texto: 'el diputado Vergara',
    espera: 'ok',
    normalizado: 'el diputado vergara',
    por: 'contiene `puta` y `verga`'
  ),
  (
    texto: 'hoy entrené piernas y me fue bien',
    espera: 'ok',
    normalizado: 'hoy entrene piernas y me fue bien',
    por: 'control: texto normal pasa'
  ),
  (texto: 'puto', espera: 'block', normalizado: 'puto', por: 'termino directo'),
  (texto: 'PUTO', espera: 'block', normalizado: 'puto', por: 'mayusculas'),
  (
    texto: 'pÚtO',
    espera: 'block',
    normalizado: 'puto',
    por: 'mayusculas mezcladas y acento'
  ),
  (
    texto: 'putooooo',
    espera: 'block',
    normalizado: 'puto',
    por: 'caracteres repetidos'
  ),
  (
    texto: 'p u t o',
    espera: 'block',
    normalizado: 'p u t o',
    por: 'separado por espacios'
  ),
  (
    texto: 'p-u-t-o',
    espera: 'block',
    normalizado: 'p-u-t-o',
    por: 'separado por guiones'
  ),
  (
    texto: 'p.u.t.o',
    espera: 'block',
    normalizado: 'p.u.t.o',
    por: 'separado por puntos'
  ),
  (texto: 'pvto', espera: 'block', normalizado: 'pvto', por: 'v por u'),
  (
    texto: 'sos un hijo de puta',
    espera: 'block',
    normalizado: 'sos un hijo de puta',
    por: 'frase de varias palabras'
  ),
  (
    texto: 'hijo  de   PUTA',
    espera: 'block',
    normalizado: 'hijo  de puta',
    por: 'frase con espacios de mas'
  ),
  (
    texto: 'te voy a matar',
    espera: 'block',
    normalizado: 'te voy a matar',
    por: 'amenaza'
  ),
  (
    texto: 'and4te a morir',
    espera: 'block',
    normalizado: 'andate a morir',
    por: 'leet: 4 -> a'
  ),
  (
    texto: 'sos un pelotudo',
    espera: 'review',
    normalizado: 'sos un pelotudo',
    por: 'insulto casual rioplatense'
  ),
  (
    texto: 'que gil',
    espera: 'review',
    normalizado: 'que gil',
    por: 'insulto leve'
  ),
  (
    texto: 'thinspo',
    espera: 'review',
    normalizado: 'thinspo',
    por: 'contenido pro trastorno alimentario'
  ),
  (
    texto: 'cuantos años entrenas por semana',
    espera: 'ok',
    normalizado: 'cuantos anos entrenas por semana',
    por:
        '`ñ` pliega a `n`: `años` -> `anos`. Vigila que nadie meta `ano` en la lista'
  ),
  (
    texto: 'hace 3 años que entreno',
    espera: 'ok',
    normalizado: 'hace e anos que entreno',
    por: 'leet `3`->`e` sobre un numero real, mas el plegado de la ñ'
  ),
  (
    texto: 'sos un puta!',
    espera: 'block',
    normalizado: 'sos un puta!',
    por:
        'el `!` final NO se traduce a `i`: si se tradujera, `putai` no matchearia'
  ),
  (
    texto: '10x3 con 90 segundos de pausa',
    espera: 'ok',
    normalizado: 'ioxe con 9o segundos de pausa',
    por:
        'notacion de series: los digitos pasan por leet y no pueden inventar un veto'
  ),
  (
    texto: 'otro loco que entrena a las 6',
    espera: 'ok',
    normalizado: 'otro loco que entrena a las 6',
    por:
        'pegado entero daria `otroloco` -> contiene `trolo`. La pasada B NO pega entre palabras'
  ),
  (
    texto: 'traeme otro lote de bandas',
    espera: 'ok',
    normalizado: 'traeme otro lote de bandas',
    por: 'mismo caso: `otrolote` contiene `trolo`'
  ),
  (
    texto: 'pvto',
    espera: 'block',
    normalizado: 'pvto',
    por: 'grafia de evasion explicita, no transformacion'
  ),
  (
    texto: 'holaputo',
    espera: 'block',
    normalizado: 'holaputo',
    por: 'pegado adentro de un token: la pasada B busca subcadena por token'
  ),
  (
    texto: 'no me controlo con la comida',
    espera: 'ok',
    normalizado: 'no me controlo con la comida',
    por: '`controlo` contiene `trolo` y esta en la allowlist'
  ),
  (
    texto: 'hice press banca con barra',
    espera: 'ok',
    normalizado: 'hice press banca con barra',
    por: 'dobles `ss` y `rr`: el colapso arranca en TRES, no en dos'
  ),
  (
    texto: 'el perro del gimnasio se llama Rocco',
    espera: 'ok',
    normalizado: 'el perro del gimnasio se llama rocco',
    por: 'tres dobles seguidas — `rr`, `ll`, `cc`'
  ),
  (
    texto: 'acción correcta en el banco',
    espera: 'ok',
    normalizado: 'accion correcta en el banco',
    por: 'doble con acento arriba: plegado y colapso se tocan'
  ),
  (
    texto: 'pu-to',
    espera: 'block',
    normalizado: 'pu-to',
    por:
        'fragmentos de 2 y 2. Con la regla vieja —corridas de UN caracter— un separador salteaba la capa entera'
  ),
  (
    texto: 'p-uto',
    espera: 'block',
    normalizado: 'p-uto',
    por: 'fragmentos de 1 y 3'
  ),
  (
    texto: 'pu to',
    espera: 'block',
    normalizado: 'pu to',
    por: 'mismo caso, separado por espacio'
  ),
  (
    texto: 'púto',
    espera: 'block',
    normalizado: 'puto',
    por:
        '`u` + U+0301 descompuesto: se ve identico a `púto` y antes pasaba, porque la marca partia el token en dos'
  ),
  (
    texto: 'mogólico',
    espera: 'block',
    normalizado: 'mogolico',
    por: 'misma descomposicion sobre otro termino'
  ),
  (
    texto: 'otro lo hizo mejor',
    espera: 'ok',
    normalizado: 'otro lo hizo mejor',
    por:
        '`otro`+`lo` pegados dan `otrolo`, que contiene `trolo`. La regla pide que los DOS fragmentos sean cortos, y `otro` no lo es'
  ),
  (
    texto: 'dale que va',
    espera: 'ok',
    normalizado: 'dale que va',
    por:
        'tres fragmentos cortos seguidos se pegan: `dalequeva` no contiene nada, y tiene que seguir siendo asi'
  ),
  (
    texto: 'con-chudo',
    espera: 'ok',
    normalizado: 'con-chudo',
    por:
        'HUECO CONOCIDO, fijado a proposito. `con`(3) y `chudo`(5): la regla no los pega porque el segundo es largo. Pegarlos igual reintroduce el falso positivo sobre `otro lo`, y un filtro que bloquea castellano corriente dura una semana. El backstop de este caso es la cola de reportes, no la lista'
  ),
];
