// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGa1H1FzTHhbDFEmjsrs20DuIUhiD8FDQ',
    appId: '1:1079774251763:android:6810a95a4b3dce9b3f8586',
    messagingSenderId: '1079774251763',
    projectId: 'treino-dev',
    storageBucket: 'treino-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADShDYyLfXvQSVgVUCoSsdXmB35uS8Z3k',
    appId: '1:1079774251763:ios:006f7766b93ce5dc3f8586',
    messagingSenderId: '1079774251763',
    projectId: 'treino-dev',
    storageBucket: 'treino-dev.firebasestorage.app',
    androidClientId: '1079774251763-kf6ct53t2olntalhafgtj5bvufpa6rfd.apps.googleusercontent.com',
    iosClientId: '1079774251763-rbcocukjq4mc8onmohitp65jualmvmo5.apps.googleusercontent.com',
    iosBundleId: 'com.backhaus.treino',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs6DDwJxEZkfWQgrhGF2_uUzWRBVweAFs',
    appId: '1:1079774251763:web:e78f5ea99effb1593f8586',
    messagingSenderId: '1079774251763',
    projectId: 'treino-dev',
    authDomain: 'treino-dev.firebaseapp.com',
    storageBucket: 'treino-dev.firebasestorage.app',
    measurementId: 'G-KT3CZ3EL8S',
  );

}